apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: q2wdfowtk-go 
  janus-idp.io/tekton: q2wdfowtk-go
  backstage.io/kubernetes-id: q2wdfowtk-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: q2wdfowtk-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  